FROM postgres:latest

# Set the timezone in the correct postgresql.conf file
#RUN echo "timezone = 'UTC'" >> /usr/local/share/postgresql/postgresql.conf.sample

# Set environment variables for Postgres
ENV POSTGRES_DB=mystore_db
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=helloworld

# Expose Postgres default port
EXPOSE 5432

